from __future__ import annotations

from ..models import ScanReport
from .console import overall_status
from .markdown import render_markdown


def _forum_title(report: ScanReport) -> str:
    crit = [f for f in report.findings if f.severity == "critical"]
    warn = [f for f in report.findings if f.severity == "warning"]
    primary = (crit or warn or [None])[0]
    if primary is None:
        return "DGX Spark scan: no issues detected"
    return f"DGX Spark {primary.title.lower()}: {primary.rule_id}"


def render_forum(report: ScanReport) -> str:
    status = overall_status(report)
    title = _forum_title(report)

    intro: list[str] = []
    intro.append(f"**Title suggestion:** {title}\n")
    intro.append(
        "This report was generated by Spark Doctor, a local diagnostic CLI for DGX Spark. "
        "It does not change system state. Personal identifiers have been redacted.\n"
    )
    intro.append(f"**Overall: {status}**\n")

    # Short TL;DR section
    tldr: list[str] = ["## TL;DR\n"]
    if not report.findings:
        tldr.append("- No issues detected by Spark Doctor.\n")
    else:
        for f in report.findings:
            tldr.append(f"- **{f.severity.upper()}** — {f.title} (`{f.rule_id}`)")
            if f.recommended_actions:
                tldr.append(f"  - Next: {f.recommended_actions[0]}")
        tldr.append("")

    body = render_markdown(report)
    # strip the outer H1 from markdown body to avoid duplication
    body = body.replace("# Spark Doctor Report\n", "", 1)

    return "\n".join(intro + tldr) + "\n" + body
